version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/data/db
  server:
    image: gregorcaf/tum-exercises:cc-exercise-02
    # build: .
    depends_on:
    - mongodb
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/booksData
    ports:
      - 3000:3000 

volumes:
  mongodb_data_container: